### ISSUE TITLE
[DO] Create branch from github, integrate with IDEA

### ISSUE THREAD

**Issue by matkarimov10** [IT-Forelead/gazon#41]

**Comment by bekzod-creator** [comment]
to create this branch 
1) create task and convert to issue via gazon 
2) open this task click to the task name 
3) ater clicking  you can see development you can see createn  branch after clicking it you can put name on branch and choose the Repository destination and click the create branch that's it

**Comment by bekzod-creator** [comment]
![Image](https://github.com/IT-Forelead/gazon/assets/64070963/5be9874d-ba82-430c-8aef-0c7ed139d9bf)

**Comment by bekzod-creator** [comment]
![Image](https://github.com/IT-Forelead/gazon/assets/64070963/561a9385-8977-4992-a3e6-6b3f2596d0ab)



![Image](https://github.com/IT-Forelead/gazon/assets/64070963/89176f3f-1115-455c-9fa6-d934284b4106)



![Image](https://github.com/IT-Forelead/gazon/assets/64070963/18937b5c-5a13-4fce-ac1f-efc809bc38d5)
